### ISSUE TITLE
Unexpected Error.

### ISSUE THREAD

**Issue by RobClarkson** [nvuillam/vscode-groovy-lint#101]
There has been an unexpected error while calling npm-groovy-lint. Please join the end of the logs in Output/GroovyLint if you report the issue.

This happens as soon as I install.

**Comment by nvuillam** [comment]
Could you post the log please ?
And eventually your type of computer / system , etc ? :)
Thanks !

**Comment by RobClarkson** [comment]
There was no log I could see...

Windows 10

**Comment by robross0606** [comment]
I'm seeing the same problem.  It is also constantly pulling me from comparison views (git diff, 2 file diff, etc.) back to the regular version of the file over and over whenever this error occurs.

**Comment by AssaelDan** [comment]
I encountered the same error, see attached log
[Untitled-1.txt](https://github.com/nvuillam/vscode-groovy-lint/files/5904813/Untitled-1.txt)

**Comment by pr0vieh** [comment]
any news about this have the same problem?

**Comment by nvuillam** [comment]
@RobClarkson @AssaelDan @pr0vieh  this should fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
