### ISSUE TITLE
Incompatible with current version '1.27.2' of VS Code

### ISSUE THREAD

**Issue by RichAngal** [nvuillam/vscode-groovy-lint#102]
Trying to install your plugin on version 1.27.2 of VS Code on MacOS throws error: 
Unable to install because, the depending extension 'nicolasvuillamy.vscode-groovy-lint' compatible with current version '1.27.2' of VS Code is not found.

**Comment by nvuillam** [comment]
@RichAngal   this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
