### ISSUE TITLE
GroovyLint: Unable to start CodeNarc Server

### ISSUE THREAD

**Issue by xhujerr** [nvuillam/vscode-groovy-lint#106]
Hello,
I'm running into issue:
`GroovyLint: Unable to start CodeNarc Server`

```
$ node --version
v12.21.0
```

I did not know how to troubleshoot this issue. Can you suggest where should I start?

I saw issue #16 where you recommend to run tests.
So I ran:
```
git clone git@github.com:nvuillam/npm-groovy-lint.git
cd npm-groovy-lint
sudo npm install jdeploy -g
npm install
npm run build
npm run test 2>&1 | tee test2.out
```

Attaching  the results: [test2.zip](https://github.com/nvuillam/vscode-groovy-lint/files/6166196/test2.zip)

Also previously I had npm-groovy-lint installed via npm. I'm not sure if that affects the tests.

Thanks for working on the npm-groovy-lint :-)

**Comment by nvuillam** [comment]
@xhujerr   this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
