### ISSUE TITLE
Unable to start CodeNarc server, Reason: unknown

### ISSUE THREAD

**Issue by rba1-source** [nvuillam/vscode-groovy-lint#149]
Unable to start CodeNarc server: {"status":1,"stdout":"","stderr":"","childJavaProcess":{"_events":{},"_eventsCount":2,"_closesNeeded":1,"_closesGot":1,"connected":false,"signalCode":null,"exitCode":1,"killed":false,"spawnfile":"java","_handle":null,"spawnargs":["java","-Xms256m","-Xmx2048m","-cp","\"c:\\Users\\username\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.7.5\\server\\node_modules\\npm-groovy-lint\\lib\\java\\CodeNarcServer.jar;c:\\Users\\username\\.vscode\\extensions\\nicolasvuillamy.vscode-groovy-lint-1.7.5\\server\\node_modules\\npm-groovy-lint\\lib\\java\\*\"","com.nvuillam.CodeNarcServer","--server"],"pid":7640,"stdin":null,"stdout":null,"stderr":null,"stdio":[null,null,null]}}
["--server"]
GroovyLint: Error running CodeNarc: 

npm-groovy-lint error: Fatal error while calling CodeNarc
Reason: unknown

undefined

(node:1908) UnhandledPromiseRejectionWarning: Error: getaddrinfo ENOTFOUND api.amplitude.com
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:67:26)
(Use `Code --trace-warnings ...` to show where the warning was created)
(node:1908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 3)
(node:1908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by rba1-source** [comment]
I get the error when I open a groovy file in VSCode and right-click "Format document". The log starts with "Start analyzing" then my filename, followed by the error.

Let me know what other info you need. Thanks.

**Comment by avnishcpatel** [comment]
I had this issue on Windows 10, so the memory limit suggested to me a 32-bit vs 64-bit issue.

I ran the spawn command manually with only -Xmx1024m (1024MB) and it ran fine.

Turns out I had JAVA_HOME set to an x86 JRE rather than an x64 one. Updated my path to point to the the [Adoptium x64 JRE] (https://adoptium.net/temurin/releases/?version=11) and it runs without error.

Still can't get it to format my gradle file though 😭

**Comment by stevenh** [comment]
Removing the 32bit version of java and installing the 64bit version fix this issue for me.

**Comment by nvuillam** [comment]
@rba1-source  this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
