### ISSUE TITLE
Troubleshooting section of vscode extension on marketplace conflicts with output

### ISSUE THREAD

**Issue by grabango-ttharp** [nvuillam/vscode-groovy-lint#170]
On the marketplace it states that Java 8 or greater is needed. Once installed in vscode it states that version 8-14 is required. I'm running java 19.

**Comment by nvuillam** [comment]
@grabango-ttharp  this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
