### ISSUE TITLE
Isn't working with no error messages on mac silicon with os Ventura

### ISSUE THREAD

**Issue by studentota2lvl** [nvuillam/vscode-groovy-lint#175]
Unfortunately plugin doesn't work without any errors. After opening Jenkinsfile I could see some turning gear on right bottom corner and that is all. 
I was trying to follow some guides posted on parallel topics, had changed several java versions, but it brought no effect
My setup:

OS Ventura 13.5.2 (22G91)

VS Code Version: 1.83.1 (Universal)
                Commit: f1b07bd25dfad64b0167beb15359ae573aecd2cc
                Date: 2023-10-10T23:46:55.789Z
                Electron: 25.8.4
                ElectronBuildId: 24154031
                Chromium: 114.0.5735.289
                Node.js: 18.15.0
                V8: 11.4.183.29-electron.0
                OS: Darwin arm64 22.6.0

openjdk version "11.0.20.1" 2023-08-24
OpenJDK Runtime Environment Temurin-11.0.20.1+1 (build 11.0.20.1+1)
OpenJDK 64-Bit Server VM Temurin-11.0.20.1+1 (build 11.0.20.1+1, mixed mode)

node v20.8.1

npm 10.1.0

Is there any thoughts around this? (npm-groovy-lint is working, and shows arrors\warn)

**Comment by nvuillam** [comment]
Fixes are on the way !

**Comment by nvuillam** [comment]
@studentota2lvl this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
