### ISSUE TITLE
Status Bar Icon Never Stops Spinning

### ISSUE THREAD

**Issue by timkelsch** [nvuillam/vscode-groovy-lint#181]
I have the latest version of Groovy lint installed on the latest version of VS Code last week. My repo is not large however the status bar icon hasn't stopped spinning since I installed the extension. I installed NVM and the latest LTS version of Node.js. Is there a way to find out why this is happening or get it to stop?

**Comment by vadym-kovryzhkin** [comment]
the same for me
in the log output it just prints: `Start analyzing filename.groovy`

**Comment by stevenh** [comment]
This will be fixed in the next release

**Comment by nvuillam** [comment]
@timkelsch @vadym-kovryzhkin this is fixed in newest release v3.0.0, thanks to the great job of @stevenh :)

Please can you confirm it works well for your case now ?
- If yes, please rate the app -> https://marketplace.visualstudio.com/items?itemName=NicolasVuillamy.vscode-groovy-lint&ssr=false#review-details
- If not, please reopen the issue and we'll check :)
