### ISSUE TITLE
lint & fix are painfully slow

### ISSUE THREAD

**Issue by docwhat** [nvuillam/vscode-groovy-lint#35]
The lint and fix are painfully slow; to the point where it isn't clear if anything is actually running or not.

I'm on a Mac.  Is there anything I can do to help troubleshoot this?

**Comment by nvuillam** [comment]
If your file is a thousand lines, I'm afraid there's not a lot we can do ( [CodeNarc](https://codenarc.github.io/CodeNarc/) contains lots of rules and it takes time to run them, for the moment I don't have an answer about how to improve its perfs ->  https://github.com/CodeNarc/CodeNarc/issues/465 )

I'm quite confident that once we'll have solved https://github.com/nvuillam/npm-groovy-lint/issues/38 , it will be ok with VsCode Groovy Lint, because if it starts the whole Java program at each onType event, it can only lead to pain :/ 

About seing what is running or not, you can hover on icon GroovyLint at the bottom right of VsCode and it displays the list of current plugin actions
![image](https://user-images.githubusercontent.com/17500430/81354799-cf11cd80-90cc-11ea-8534-329c8b3ed1ac.png)

**Comment by nvuillam** [comment]
Addendum: I updated npm-groovy-lint and vscode-groovy-lint to improve allocated JVM memory.
On my computer it is faster, it may solve your issue (if not i'm still really interested by your output logs from "GroovyLint" section, after you have activated debug option )

![image](https://user-images.githubusercontent.com/17500430/81427684-6de50b00-915b-11ea-91ab-5579be059f65.png)

![image](https://user-images.githubusercontent.com/17500430/81427722-79383680-915b-11ea-85d4-b75150fb57f6.png)

**Comment by docwhat** [comment]
🎉 

That  is much much faster; about 1-2  seconds!

**Comment by nvuillam** [comment]
Great :)
