### ISSUE TITLE
When a groovy file is done being linted, that file becomes automatically focused

### ISSUE THREAD

**Issue by hak33m16** [nvuillam/vscode-groovy-lint#98]
To reproduce:
* Edit text in a groovy file
* Quickly switch tabs to another file

The linter is still running in the background, and once it's completed, your focus will automatically be switched back to the file you moved away from

**Comment by justin6case** [comment]
This is a duplicate of the issue I reported #94.

**Comment by tomerpar** [comment]
happens to me too

this issue is aggravated if the files being edited are very big, linting may take few seconds to finish on file A in pane A, switch over to file B in pane B - start typing... 

as soon as lint finishes on file A - it is opened and focused in paneB replacing the current focus.

i switched to analyzing files manually ( not onChange) but that's a pain, the extention works flawlessly otherwise - thanks, great job!

**Comment by robross0606** [comment]
Same here.  This was frustrating to the point that I had to disable the plugin.

**Comment by robross0606** [comment]
> switched to analyzing files manually ( not onChange)

@tomerpar how did you do this?  Were you able to do it just for groovy files?

**Comment by kf6kjg** [comment]
Also happening here. Don't change the focus, period - that's my job as a user, not a linter's job. In my case it's taking many seconds for the lint job to complete, and I've long since moved on into a different tag group, and suddenly the files I was editing in a different tab group suddenly show up in my current tab group. Very distracting from what' I'm trying to work on.

Reproduce the problem I'm seeing:

1. Make and install a test build of this project that has a several second delay built in when it processes the lint.
2. Open several tabs of groovy files across multiple tab groups in VSCode. No duplicate tabs.
3. Save a groovy file in one tab group, click on file in another tab group to change tab group context.
4. Wait.
5. Observe that the files you saved in the first tab group suddenly show up in your current tab group. Not helpful.

I suspect this was supposed to be a feature to point out active errors. Please don't. That's the job of the Problems pane.

**Comment by dalgarin** [comment]
I often code in the vscode diff view to help track changes I am making and to have access to the old code as I am refactoring.  This is almost impossible when I am coding in groovy and the `groovyLint.lint.trigger` is set to `onType` as this bug will switch me away from the diff tab to the actual file tab after making each change.  I tested using the `onSave` trigger, and while definitely more usable, still switches away from the diff view every time I save to see updated lint results.  

I do not have this issue with any other languages/linters so does not appear to be an issue inherent to the vscode plugin platform.  Would really like to see this behavior resolved.

**Comment by l3ender** [comment]
I am facing this same issue primarily when comparing/diffing two files. Having focus always switch from the diff window to the updated file is very annoying!

**Comment by nvuillam** [comment]
i agree with all of you but I cruelly lack of available time to work on npm-groovy-lint / VsCode Groovy Lint

Would anyone you want to try a PR ? :)

**Comment by PanovEduard** [comment]
Confirm the same behavior. Even worse, if you are working on a large project, the Linter arbitrarily starts to check entire folders.
